# Generated by Django 5.2.5 on 2025-08-22 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('security', '0004_arduinodevice_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pir_motion', models.BooleanField(default=False)),
                ('glass_break', models.BooleanField(default=False)),
                ('door_open', models.BooleanField(default=False)),
                ('panic_button', models.BooleanField(default=False)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='security.arduinodevice')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('motion', 'Обнаружено движение'), ('glass', 'Разбитие стекла'), ('door', 'Открытие двери'), ('panic', 'Паническая кнопка')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('device_name', models.CharField(max_length=100)),
                ('device_address', models.CharField(blank=True, max_length=255, null=True)),
                ('owner_id', models.IntegerField()),
                ('owner_username', models.CharField(max_length=150)),
                ('owner_full_name', models.CharField(max_length=150)),
                ('owner_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='security.arduinodevice')),
                ('sensor_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sensor.sensordata')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
