# Generated by Django 5.2.5 on 2025-08-23 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorBuffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pir_motion', models.BooleanField(default=False)),
                ('glass_break', models.BooleanField(default=False)),
                ('door_open', models.BooleanField(default=False)),
                ('panic_button', models.BooleanField(default=False)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('created_alert', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_buffer', to='security.arduinodevice')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pir_motion', models.BooleanField(default=False)),
                ('glass_break', models.BooleanField(default=False)),
                ('door_open', models.BooleanField(default=False)),
                ('panic_button', models.BooleanField(default=False)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('triggered_sensors_count', models.IntegerField(default=0, help_text='Количество сработавших датчиков')),
                ('is_valid_alert', models.BooleanField(default=False, help_text='Прошла ли проверку на валидность')),
                ('work_time_status', models.BooleanField(default=True, help_text='Было ли рабочее время при получении')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='security.arduinodevice')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('motion', 'Обнаружено движение'), ('glass', 'Разбитие стекла'), ('door', 'Открытие двери'), ('panic', 'Паническая кнопка'), ('multi_sensor', 'Множественное срабатывание')], max_length=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('device_name', models.CharField(max_length=100)),
                ('device_address', models.CharField(blank=True, max_length=255, null=True)),
                ('owner_id', models.IntegerField()),
                ('owner_username', models.CharField(max_length=150)),
                ('owner_full_name', models.CharField(max_length=150)),
                ('owner_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('triggered_sensors', models.JSONField(default=list, help_text='Список сработавших датчиков')),
                ('sensors_count', models.IntegerField(default=1, help_text='Количество сработавших датчиков')),
                ('confidence_level', models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая')], default='medium', max_length=10)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='security.arduinodevice')),
                ('sensor_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sensor.sensordata')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='sensordata',
            index=models.Index(fields=['device', '-timestamp'], name='sensor_sens_device__cc431a_idx'),
        ),
        migrations.AddIndex(
            model_name='sensordata',
            index=models.Index(fields=['is_valid_alert', '-timestamp'], name='sensor_sens_is_vali_c832a2_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['device', '-timestamp'], name='sensor_aler_device__833262_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['is_acknowledged', '-timestamp'], name='sensor_aler_is_ackn_fae04a_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['alert_type', '-timestamp'], name='sensor_aler_alert_t_1ae70c_idx'),
        ),
    ]
