# Generated by Django 5.2.5 on 2025-08-23 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorbuffer',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='sensorbuffer',
            name='temperature',
        ),
    ]
