# Generated by Django 5.2.5 on 2025-08-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arduinodevice',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
