# Generated by Django 5.2.5 on 2025-08-22 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_alter_arduinodevice_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arduinodevice',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arduino_devices', to=settings.AUTH_USER_MODEL),
        ),
    ]
